/*
 * Copyright (c) 2024 Arthur Araujo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package cc.wordview.app.extractor

import org.schabi.newpipe.extractor.stream.StreamInfo

fun getSubtitleFor(id: String, language: String): String? {
    val info = StreamInfo.getInfo(YTService,"https://youtube.com/watch?v=$id")

    for (subtitle in info.subtitles) {
        if (subtitle.isAutoGenerated) continue

        if (subtitle.languageTag == language) {
            return subtitle.content.replace("&fmt=ttml", "&fmt=vtt")
        }
    }

    return null
}

