/*
 * Copyright (c) 2024 Arthur Araujo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package cc.wordview.app.extractor

import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.StreamingService
import org.schabi.newpipe.extractor.stream.StreamInfo

class VideoStream {
    lateinit var info: StreamInfo
    var searchQuery = ""

    fun init(id: String) {
        info = StreamInfo.getInfo(YTService, "https://youtube.com/watch?v=$id")

        // For now doing this is ok but as the filter grows
        // a less repetitive solution should be created
        val artistClean = info.uploaderName.lowercase()
            .replace("official", "")
            .replace("channel", "")

        val titleClean = info.name.lowercase()
            .replace("\\[[^\\[]*\\]", "")
            .replace("[", "")
            .replace("]", "")
            .replace("mv", "")
            .replace("music video", "")
            .replace(
                "歌ってみた",
                ""
            )

        searchQuery = "$titleClean $artistClean"
    }

    fun getStreamURL(): String {
        return info.audioStreams[0].content
    }

    fun getHQThumbnail(): String {
        return info.thumbnails.last().url
    }

    fun getTitle(): String {
        return info.name
    }

    fun getSubtitleURL(langTag: String): String {
        var subtitleURL = ""
        for (subtitle in info.subtitles) {
            if (subtitle.isAutoGenerated) continue

            if (subtitle.languageTag == langTag) {
                subtitleURL = subtitle.content.replace("&fmt=ttml", "&fmt=vtt")
            }
        }

        return subtitleURL
    }

    companion object {
        var YTService: StreamingService = NewPipe.getService(0);
    }
}